= WebFX Documentation
:icons: font
:toc: left
:toclevels: 2
Last updated: {docdate}

== Introduction


=== What is WebFX?

WebFX is a JavaFX application transpiler powered by link:https://www.gwtproject.org[GWT^]. It can transpile a JavaFX application into a traditional self-contained pure JavaScript web app (with no plugin or server required for its execution in the browser).

=== How it works

[.text-center]
[plantuml, webfx-how-it-works, format=svg]
----
skinparam ranksep 5
skinparam nodesep 5

rectangle "OpenJFX" {
    node "Higher layer" as o1
    node "Lower layer" as o2
}
o1 --[hidden]> o2

usecase "Patching\nprocess" as pp
usecase "Replaced\nby" as rb
pp --[hidden]> rb

rectangle "WebFX kit" {
    node "GWT compatible\n        version" as w1
    node "  Scene graph -> DOM\n            mapper" as w2
}
w1 --[hidden]> w2

rectangle "Your repository" {
    node "Your JavaFX app" as app
    usecase "GWT" as gwt
    node "Web app" as wa
}

o1 -r-> pp
pp -r-> w1

o2 -r-> rb
rb -r-> w2

app -[dotted]> o1: uses JavaFX API

app -d-> gwt
w1 -r-> gwt
w2 -r-> gwt
gwt -d-> wa

' Adding more hidden arrows to force vartical alignment of elements in the "Your repository" rectangle
app -[hidden]> gwt
app -[hidden]> gwt
gwt -[hidden]> wa
----

The link:https://github.com/webfx-project/webfx/tree/main/webfx-kit[webfx-kit^] module is the heart of WebFX. It's a modified version of OpenJFX that can be transpiled. This is achieved by patching the higher layer of OpenJFX (which contains the main JavaFX features and API) to make it GWT compatible, and by replacing the lower layer (the graphic rendering pipeline) by a scene graph -> DOM mapper (the DOM being finally rendered by the browser).

=== Limitations

The WebFX kit coverage is for now limited to the essential features of JavaFX. So to successfully compile to the web, your JavaFX app needs to meet these 2 requirements:

* use only the features covered by the WebFX kit (you can check out the link:https://javadoc.webfx.dev[JavaDoc^] to get an idea of this coverage)
* be compatible with GWT (no reflection, no multi-threading, no blocking code, etc...)

A JavaFX application that meets these 2 requirements is called a _WebFX application_, and it can be transpiled to the web simply by running a GWT compilation of it together with the WebFX kit.

NOTE: Note for the impatient: OpenJFX is a very rich and big library (about 10MB) compared to standard JS frameworks (typically 100KB). It will take time to complete its coverage (some parts may not be possible). Thanks for your understanding. But compared to some frameworks, you can already do a lot with the current coverage.

=== Benefits

==== Full-stack Java

==== Performance

==== Fast development cycles

You don't need to run regular GWT compilations like you would do with a traditional GWT development. Instead, you mainly develop, run, and debug your WebFX application directly in your preferred Java IDE with the OpenJFX runtime (like a standard JavaFX development). You transpile it only from time to time to test the web app.

==== Cross-platform

[.text-center]
[graphviz, webfx-cross-platform, format=svg]
----
digraph {
    "Your WebFX application" -> "Web\nAll major browsers" [headlabel="WebFX" labeldistance=4.5 labelangle=20];
    "Your WebFX application" -> "Desktop\nWindows, macOS & Linux" [headlabel="JavaFX or Gluon" labeldistance=2.7 labelangle=-7];
    "Your WebFX application" -> "Mobiles\nAndroid & iOS" [label="Gluon"];
}
----

WebFX opens the door to a full cross-platform development from a single source code base. In addition to the web platform, your WebFX application can indeed also be compiled for the desktop & mobiles thanks to the JavaFX & Gluon toolchains.

== Getting started

=== Prerequisite

To develop WebFX applications, you will need the following software already installed on your development machine:

 * JDK 13 or above
 * Maven
 * Git
 * Your preferred Java IDE

IMPORTANT: Be sure that `java`, `mvn` and `git` are in the path of your terminal. The WebFX CLI will invoke these commands without specifying their full path.

=== Introducing the WebFX CLI

The WebFX CLI is a Command Line Interface tool that will assist you developing WebFX applications. It will create your application modules as follows:

[plantuml, webfx-app-structure, format=svg]
----
skinparam Legend {
	BackgroundColor transparent
	BorderColor transparent
    FontSize 18
    FontColor #444
}
legend
Your repository
|_ xxx-application (1)
|_ xxx-application-gluon (2)
|_ xxx-application-gwt (3)
|_ xxx-application-openjfx (4)
end legend
----
<1> This module contains the JavaFX code of your application. It is cross-platform (not yet bound to a specific platform) and therefore not executable.
<2> This module targets the native desktop & mobile platforms. It binds your application with the OpenJFX runtime, and can call the Gluon toolchain to produce the Windows, macOS, Linux, Android & iOS native executables (depending on your OS).
<3> This module targets the web platform. It binds your application with the WebFX kit, and can call GWT to produce the web app.
<4> This module targets the standard desktop platform. It binds your application with the OpenJFX runtime. It is directly executable in your IDE. It can also call the standard JavaFX toolchain to produce the desktop executables (Windows, macOS or Linux) with an embed JVM.

You can create several WebFX applications in the same repository. If your application code grows, you can split your code into more modules. The WebFX CLI will help you to create and maintain all your modules. For each module, it will create and maintain your build files as follows (when applicable to the module):

[graphviz, wbfx-cli, format=svg]
----
digraph {
    "webfx-cli" [shape=rectangle];
    "webfx.xml" -> "webfx-cli"
    "Your module source code" -> "webfx-cli"
    "webfx-cli" -> "pom.xml"
    "webfx-cli" -> "module-info.java"
    "webfx-cli" -> "GWT module.gwt.xml
super sources, bundles, etc..."
    "webfx-cli" -> "GraalVM conf"
}
----

Your inputs will be centralized in the WebFX module files named webfx.xml (same location as pom.xml), and the WebFX CLI will generate the rest of the build chain from these webfx.xml files. For example, a typical directive in webfx.xml will be:

    <dependencies>
        <used-by-source-modules/>
    </dependencies>

This directive is asking the WebFX CLI to generate the list of your dependencies from an analysis of your source code, and automatically populate the dependencies in pom.xml.

In that process, the WebFX CLI takes care of the cross-platform aspects: when a feature is platform-dependent (a different implementation exists for different platforms), the tool will pick up the right modules (those whose implementation matches the target platform). In particular, it will replace the OpenJFX modules with the WebFX kit ones when targeting the web.

=== Installing the WebFX CLI

Since we haven't published any release at this stage yet, the way to install the WebFX CLI for now is to clone the https://github.com/webfx-project/webfx-cli[webfx-cli] repository, and build it with Maven.

NOTE: We will distribute the WebFX CLI in a better way with the first official release.

==== Cloning the webfx-cli repository

[source,shell,indent=0,role="primary"]
.HTTPS
----
git clone https://github.com/webfx-project/webfx-cli.git
----

[source,shell,indent=0,role="secondary"]
.SSH
----
git clone git@github.com:webfx-project/webfx-cli.git
----

==== Building webfx-cli with Maven

This is achieved by running the Maven _package_ goal under the webfx-cli directory:

 cd webfx-cli
 mvn package

IMPORTANT: As previously mentioned, WebFX CLI requires JDK 13 or above to successfully compile.

This generates an executable fat jar in the target folder that we can execute with java:

 java -jar target/webfx-cli-0.1.0-SNAPSHOT-fat.jar --help

==== Creating a permanent _webfx_ alias

To easily invoke the WebFX CLI from a terminal, we need to create a permanent _webfx_ alias. This is done with the following command (to run under the webfx-cli directory):

[source,shell,indent=0,role="primary"]
.Linux
----
echo "alias webfx='java -jar $(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")/target/webfx-cli-0.1.0-SNAPSHOT-fat.jar'" >> ~/.bashrc <1>

source ~/.bashrc <2>
----
<1> Adding the alias to the shell profile
<2> Applying it to the current session

[source,shell,indent=0,role="secondary"]
.macOS >= Catalina
----
echo "alias webfx='java -jar $(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")/target/webfx-cli-0.1.0-SNAPSHOT-fat.jar'" >> ~/.zshrc <1>

source ~/.zshrc <2>
----
<1> Adding the alias to the shell profile
<2> Applying it to the current session

[source,shell,indent=0,role="secondary"]
.macOS < Catalina
----
echo "alias webfx='java -jar $(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")/target/webfx-cli-0.1.0-SNAPSHOT-fat.jar'" >> ~/.bash_profile <1>

source ~/.bash_profile <2>
----
<1> Adding the alias to the shell profile
<2> Applying it to the current session

[source,shell,indent=0,role="secondary"]
.Windows PowerShell
----
If (!(Test-Path $profile)) { New-Item -Path $profile -Force } <1>

"`r`nfunction webfx([String[]] [Parameter(ValueFromRemainingArguments)] `$params) { java -jar $((Get-Item .).fullName)\target\webfx-cli-0.1.0-SNAPSHOT-fat.jar `$params }`r`n" >> $profile <2>

If ($(Get-ExecutionPolicy) -eq "Restricted") { Start-Process powershell -Verb runAs "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned" -Wait } <3>

. $profile <4>
----
<1> Creating a PowerShell profile if it doesn't exist
<2> Adding the alias (implemented as a function) to it
<3> Lowering the execution policy if necessary to execute the profile
<4> Applying it to the current session

Then you should be able to invoke the CLI tool from the terminal:

 webfx --help

==== Updating the WebFX CLI to the latest version

You can check for update at anytime by running:

 webfx bump cli

If a new version is available, it will download it and build it.

NOTE: This is the only command that uses `git`, and it's just a `git pull` of the webfx-cli repository. The tool will not call `git` on your own repositories.

=== Creating your first WebFX app

==== Creating and initializing your repository

Let's create our first WebFX application. We need to create the repository folder and ask the WebFX CLI to initialize it, passing it the groupId, artifactId and version of our application.

 mkdir webfx-example
 cd webfx-example
 webfx init org.example:webfx-example:1.0.0-SNAPSHOT

TIP: `webfx init org.example:1.0.0-SNAPSHOT` will also work as the tool takes the repository directory name as the artifactId if omitted in the command.

==== Creating your application modules

 webfx create application --class org.example.webfxexample.WebFxExampleApplication --helloWorld

[plantuml, webfx-example-structure, format=svg]
----
skinparam Legend {
	BackgroundColor transparent
	BorderColor transparent
    FontSize 18
    FontColor #444
}
legend
webfx-example
|_ webfx-example-application
|_ webfx-example-application-gluon
|_ webfx-example-application-gwt
|_ webfx-example-application-openjfx
end legend
----
==== Building your application

 webfx build

==== Running your application

You can run the OpenJFX version of your application with the following command:

 webfx -m webfx-example-application-openjfx run

You can run the GWT version of your application with the following command:

 webfx -m webfx-example-application-gwt run

=== Developing in your IDE

We will give the instructions for IntelliJ IDEA, but you should be able to easily transpose them to other Java IDEs.

==== Opening the project

==== Configuring the OpenJFX application

GWT has a different entry point than standard Java applications, but WebFX hides the hassle with a single cross-platform entry point. So the main class of a WebFX application will always be `dev.webfx.platform.shared.services.boot.ApplicationBooter` which will correctly bootstrap your application whatever the target platform. It will find your JavaFX application because it has been automatically declared as a Java service by the WebFX CLI.

NOTE: GWT normally doesn't support the Java service API, but WebFX does, because the CLI emulates it by generating a GWT super source. You can rely on this feature to declare and implement your own services. Your services can even be platform-dependent, and you can write a specific implementation for each platform. This can be a UI API, with an OpenJFX implementation, and then a GWT implementation using the JS library you want for your web app.

==== Building and running the GWT application

==== Making changes

 webfx update

ifdef::backend-html5[]
== PDF version
Here is the
link:WebFX.pdf[PDF version,float="right"]
of this documentation.
endif::[]
