= WebFX Documentation
:icons: font
:toc: left
:toclevels: 2
Last updated: {docdate}

== Introduction

WebFX is a JavaFX application transpiler that produces a pure JS web app (no plugin, no server). It works as follows:

[plantuml, format=svg, opts="inline"]
----
skinparam ranksep 5
skinparam nodesep 5

node "Your JavaFX app" as app

rectangle "OpenJFX" {
node "     High level\nImplementation" as o1
node "  Low level\nImplentation" as o2
}
o1 --[hidden]> o2

usecase "Patching\nprocess" as pp
usecase "Replaced\nby" as rb

rectangle "WebFX Kit" {
node "GWT compatible\n        version" as w1
node "  Scene graph -> DOM\n            mapper" as w2
}
w1 --[hidden]> w2

pp --[hidden]> rb

usecase "GWT" as gwt

node "Web app" as wa


o1 -r-> pp
pp -r-> w1

o2 -r-> rb
rb -r-> w2

app -d-> gwt
w1 -r-> gwt
w2 -r-> gwt
gwt -d-> wa

gwt --[hidden]> w2
----

== Getting started

=== Prerequisite

To develop WebFX applications, you will need the following software already installed on your development machine:

 * JDK 13 or above
 * Maven
 * Git
 * Your preferred Java IDE

IMPORTANT: Be sure that you can invoke `java`, `mvn` and `git` directly from the terminal. The WebFX CLI will invoke `mvn` and `java` without specifying their full path.

=== Introducing the WebFX CLI

The WebFX CLI is the Command Line Interface for WebFX. It's an essential tool to assist you developing WebFX applications. It will create your application modules as follows:

[plantuml, format=svg, opts="inline"]
----
skinparam Legend {
	BackgroundColor transparent
	BorderColor transparent
    FontSize 18
    FontColor #444
}
legend
|_ xxx-application (1)
|_ xxx-application-gluon (2)
|_ xxx-application-gwt (3)
|_ xxx-application-openjfx (4)
end legend
----
<1> This module contains the JavaFX code of your application. It is not directly executable as it is not yet bound to a specific platform.
<2> This module targets the mobile platforms. It will call the Gluon toolchain to produce the Android / iOS executables.
<3> This module targets the web platform. It will call GWT to produce the HTML and JS code.
<4> This module targets the desktop platform. It will create an executable Java artifact with the OpenJFX runtime. You can also use this module to directly run and debug your application in your IDE.

You can create several WebFX applications in the same repository, such as a front office and a back office for example. Of course, if your application code grows, you can split your code into additional modules. The WebFX CLI will help you to create and maintain all your modules. For each module, it will create and maintain your build files, such as (when applicable):

* pom.xml (Maven module files)
* module-info.java (Java module files)
* module.gwt.xml (GWT module files)
* and some other files required for a successful compilation

[graphviz, format=svg, opts="inline"]
----
digraph {
    "webfx-cli" [shape=rectangle];
    "webfx.xml" -> "webfx-cli"
    "Your module source code" -> "webfx-cli"
    "webfx-cli" -> "pom.xml"
    "webfx-cli" -> "module-info.java"
    "webfx-cli" -> "GWT module.gwt.xml
super sources, bundles, etc..."
    "webfx-cli" -> "GraalVM conf"
}
----

Your inputs will be centralized in the WebFX module files named webfx.xml, and the WebFX CLI will generate the rest of the build chain from these webfx.xml files. For example, a typical directive in webfx.xml will be:

    <dependencies>
        <used-by-source-modules/>
    </dependencies>

This directive is asking the WebFX CLI to automatically generate the list of your dependencies from an analysis of your source code.

The tool takes over the aspects of cross-platform development: when a feature is platform-dependent (a different implementations exists for each platform), the tool will pick up the right modules in the final executable modules (the ones matching the platform targeted by the module).

=== Installing the WebFX CLI

We haven't published any release at this stage yet, so the way to install the WebFX CLI for now is to clone the https://github.com/webfx-project/webfx-cli[webfx-cli] repository, and build it with Maven.

NOTE: We will distribute the WebFX CLI in a better way later, when we will publish the first official release.

==== Cloning the webfx-cli repository


[source,shell,indent=0,role="primary"]
.HTTPS
----
git clone https://github.com/webfx-project/webfx-cli.git
----

[source,shell,indent=0,role="secondary"]
.SSH
----
git clone git@github.com:webfx-project/webfx-cli.git
----

==== Building webfx-cli with Maven

This is achieved by running the Maven _package_ goal under the webfx-cli directory:

 cd webfx-cli
 mvn package

IMPORTANT: As previously mentioned, WebFX CLI requires JDK 13 or above (you will get a build error with lower versions).

This generates an executable fat jar in the target folder that we can execute with java:

 java -jar target/webfx-cli-0.1.0-SNAPSHOT-fat.jar --help

==== Creating a permanent _webfx_ alias

To easily invoke the WebFX CLI from a terminal, we need to create a permanent _webfx_ alias to it. This is done with the following command (to run under the webfx-cli directory):

[source,shell,indent=0,role="primary"]
.Linux
----
echo "alias webfx='java -jar $(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")/target/webfx-cli-0.1.0-SNAPSHOT-fat.jar'" >> ~/.bashrc <1>

source ~/.bashrc <2>
----
<1> Adding the alias to the shell profile
<2> Applying it to the current session

[source,shell,indent=0,role="secondary"]
.macOS >= Catalina
----
echo "alias webfx='java -jar $(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")/target/webfx-cli-0.1.0-SNAPSHOT-fat.jar'" >> ~/.zshrc <1>

source ~/.zshrc <2>
----
<1> Adding the alias to the shell profile
<2> Applying it to the current session

[source,shell,indent=0,role="secondary"]
.macOS < Catalina
----
echo "alias webfx='java -jar $(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")/target/webfx-cli-0.1.0-SNAPSHOT-fat.jar'" >> ~/.bash_profile <1>

source ~/.bash_profile <2>
----
<1> Adding the alias to the shell profile
<2> Applying it to the current session

[source,shell,indent=0,role="secondary"]
.Windows PowerShell
----
If (!(Test-Path $profile)) { New-Item -Path $profile -Force } <1>

"`r`nfunction webfx([String[]] [Parameter(ValueFromRemainingArguments)] `$params) { java -jar $((Get-Item .).fullName)\target\webfx-cli-0.1.0-SNAPSHOT-fat.jar `$params }`r`n" >> $profile <2>

If ($(Get-ExecutionPolicy) -eq "Restricted") { Start-Process powershell -Verb runAs "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned" -Wait } <3>

. $profile <4>
----
<1> Creating a PowerShell profile if it doesn't exist
<2> Adding the alias (implemented as a function) to it
<3> Lowering the execution policy if necessary to execute the profile
<4> Applying it to the current session

Then you should be able to invoke the CLI tool from the terminal:

 webfx --help

==== Updating the WebFX CLI to the latest version

If later you want to update the WebFX CLI to the latest SNAPSHOT version, you just need to update your local repository and rebuild it with Maven. This is done through the following commands (under your webfx-cli local folder):

 git pull
 mvn package

=== Creating your first WebFX app

==== Creating and initializing your repository

Let's create our first WebFX application. We need to create the repository folder and ask the WebFX CLI to initialize it, passing it the groupId, artifactId and version of our application.

 mkdir webfx-example
 cd webfx-example
 webfx init org.example webfx-example 1.0.0-SNAPSHOT

==== Creating your application modules

 webfx create application --class org.example.webfxexample.WebFxExampleApplication --helloWorld

[plantuml, format=svg, opts="inline"]
----
skinparam Legend {
	BackgroundColor transparent
	BorderColor transparent
    FontSize 18
    FontColor #444
}
legend
|_ webfx-example-application
|_ webfx-example-application-gluon
|_ webfx-example-application-gwt
|_ webfx-example-application-openjfx
end legend
----
==== Building your application

 webfx build

==== Running your application

You can run the OpenJFX version of your application with the following command:

 webfx -m webfx-example-application-openjfx run

You can run the GWT version of your application with the following command:

 webfx -m webfx-example-application-gwt run

=== Developing in your IDE

We will give the instructions for IntelliJ IDEA, but you should be able to easily transpose them to other Java IDEs such as NetBeans or Eclipse.

==== Opening the project

==== Configuring the OpenJFX application

==== Building and running the GWT application

==== Making changes

 webfx update

ifdef::backend-html5[]
== PDF version
You can also download this
link:WebFX.pdf[PDF version,float="right"]
of the documentation.
endif::[]
