= WebFX Documentation
:icons: font
:toc: left
:toclevels: 2
Last updated: {docdate}

== Introduction


=== What is WebFX?

WebFX is a JavaFX application transpiler powered by link:https://www.gwtproject.org[GWT^]. It can transpile a JavaFX application into a traditional self-contained pure JavaScript web app (with no plugin or server required for its execution in the browser).

=== How it works

[.text-center]
[plantuml, webfx-how-it-works, format=svg]
----
skinparam ranksep 5
skinparam nodesep 5

rectangle "OpenJFX" {
    node "Higher layer" as o1
    node "Lower layer" as o2
}
o1 --[hidden]> o2

usecase "Patching\nprocess" as pp
usecase "Replaced\nby" as rb
pp --[hidden]> rb

rectangle "WebFX kit" {
    node "GWT compatible\n        version" as w1
    node "  Scene graph -> DOM\n            mapper" as w2
}
w1 --[hidden]> w2

rectangle "Your repository" {
    node "Your JavaFX app" as app
    usecase "GWT" as gwt
    node "Web app" as wa
}

o1 -r-> pp
pp -r-> w1

o2 -r-> rb
rb -r-> w2

app -[dotted]> o1: uses JavaFX API

app -d-> gwt
w1 -r-> gwt
w2 -r-> gwt
gwt -d-> wa

' Adding more hidden arrows to force vartical alignment of elements in the "Your repository" rectangle
app -[hidden]> gwt
app -[hidden]> gwt
gwt -[hidden]> wa
----

The link:https://github.com/webfx-project/webfx/tree/main/webfx-kit[webfx-kit^] module is the heart of WebFX. It's a modified version of OpenJFX that can be transpiled. This is achieved by patching the higher layer of OpenJFX (which contains the main JavaFX features and API) to make it GWT compatible, and by replacing the lower layer (the graphic rendering pipeline) by a scene graph -> DOM mapper (the DOM being finally rendered by the browser).

=== Limitations

The WebFX kit coverage is for now limited to the essential features of JavaFX. So to successfully compile to the web, your JavaFX code needs to meet these 2 requirements:

* use only the features covered by the WebFX kit (you can check out the link:https://javadoc.webfx.dev[JavaDoc^] to get an idea of this coverage)
* be compatible with GWT (no reflection, no multi-threading, no blocking code, etc...)

When a JavaFX application meets these 2 requirements, we will call it a _WebFX application_, and it can be transpiled to the web simply by running a GWT compilation of it together with the WebFX kit.

NOTE: Note for the impatient: OpenJFX is a huge library (about 10MB) compared to standard JS frameworks (typically 100KB). It will take time to complete its coverage (some parts may not be possible). Thanks for your understanding. But compared to some frameworks, you can already do a lot with the current coverage.

=== Benefits

==== No server

There are already great solutions to run Swing or JavaFX applications in the browser without plugins by actually running them on a server. And these solutions don't have the limitations WebFX currently has. However, a standard self-contained JS packaging is a much more simple, scalable and reliable execution model. This is precisely that benefit that makes WebFX different, and probably the main reason why you would prefer it over the other existing solutions.

==== Performance

Despite the big size of OpenJFX, WebFX can produce lightweight web apps, as demonstrated by the demos and the website:

[cols="1,^1"]
|===
|WebFX application | JS size *

|link:https://colorfulcircles.webfx.dev[Colorful circles demo^]
|90.6 kB
|link:https://particles.webfx.dev[Particles demo^]
|90.3 kB
|link:https://tallycounter.webfx.dev[Tally counter demo^]
|101 kB
|link:https://moderngauge.webfx.dev[Modern gauge demo^]
|139 kB
|link:https://enzoclocks.webfx.dev[Enzo clocks demo^]
|253 kB
|link:https://fx2048.webfx.dev[FX2048 demo^]
|178 kB
|link:https://spacefx.webfx.dev[SpaceFX demo^]
|139 kB
|link:https://raytracer.webfx.dev[Ray tracer demo^]
|135 kB
|link:https://mandelbrot.webfx.dev[Mandelbrot demo^]
|142 kB
|link:https://preview.webfx.dev[Website^]
|218 kB
|===

[small]#* compressed JS size transiting over the network, without eventual images or other resources#

The secret? Here are the 3 main ingredients that make the magic:

* The scene graph -> DOM mapper is much thinner than the original OpenJFX lower layer which has to reimplement many features a browser already has.
* GWT runs a dead code elimination, which removes the JavaFX classes not used by the WebFX application.
* GWT produces an amazingly compaq and optimized JS code.

The later point also confers an excellent execution speed to your web app.

==== Cross-platform

[.text-center]
[graphviz, webfx-cross-platform, format=svg]
----
digraph {
    "Your WebFX application" -> "Web\nAll major browsers" [headlabel="WebFX" labeldistance=4.5 labelangle=20];
    "Your WebFX application" -> "Desktop\nWindows, macOS & Linux" [headlabel="JavaFX or Gluon" labeldistance=2.7 labelangle=-7];
    "Your WebFX application" -> "Mobiles\nAndroid & iOS" [label="Gluon"];
}
----

In addition to the web platform, WebFX will help you to compile your application for the desktop & mobiles thanks to the JavaFX & Gluon toolchains. You can do a full cross-platform development from a single source code base.

==== Java full-stack

Writing your whole stack in Java is a big advantage, keeping your environment simple and homogenous from a single Java IDE. Not only you don't need to master other complex ecosystems such as JavaScript or TypeScript, but you can also share the common code between your backend and frontends with the Java module system, a great advantage compared to heterogeneous systems.

==== Low learning curve

WebFX is not yet another UI toolkit to learn, but nothing else than the already well known and documented JavaFX API. All the powerful features you love like JavaFX bindings available for your web app. You will just feel at home with WebFX!

==== Fast development cycles

You don't need to run regular GWT compilations like you would do with a traditional GWT development, because you can run and debug your WebFX application directly in your Java IDE first with the OpenJFX runtime. You typically transpile your app only at the end of a development cycle to check the web version, after you have finished developing a feature using the standard JavaFX development model.

==== Free and open source

WebFX is an open source initiative under Apache 2.0 license.

== Getting started

=== Prerequisite

To develop WebFX applications, you will need the following software already installed on your development machine:

 * JDK 13 or above
 * Maven
 * Git
 * Your preferred Java IDE

IMPORTANT: Be sure that `java`, `mvn` and `git` are in the path of your terminal. The WebFX CLI will invoke these commands without specifying their full path.

=== Introducing the WebFX CLI

The WebFX CLI is a Command Line Interface tool that will assist you developing WebFX applications. It will create your application modules as follows:

[plantuml, webfx-app-structure, format=svg]
----
skinparam Legend {
	BackgroundColor transparent
	BorderColor transparent
    FontSize 18
    FontColor #444
}
legend
Your repository
|_ xxx-application (1)
|_ xxx-application-gluon (2)
|_ xxx-application-gwt (3)
|_ xxx-application-openjfx (4)
end legend
----
<1> This module contains the JavaFX code of your application. It is cross-platform (not yet bound to a specific platform) and therefore not executable.
<2> This module targets the native desktop & mobile platforms. It binds your application with the OpenJFX runtime, and can call the Gluon toolchain to produce the Windows, macOS, Linux, Android & iOS native executables (depending on your OS).
<3> This module targets the web platform. It binds your application with the WebFX kit, and can call GWT to produce the web app.
<4> This module targets the standard desktop platform. It binds your application with the OpenJFX runtime, and is directly executable in your IDE. It can also call the standard JavaFX toolchain to produce the desktop executables (Windows, macOS or Linux) with an embed JVM.

You can create several WebFX applications in the same repository. If your application code grows, you can split your code into more modules. The CLI will help you to create and maintain all your modules. For each module, it will create and maintain your build files as follows (when applicable to the module):

[.text-center]
[graphviz, wbfx-cli, format=svg]
----
digraph {
    node [ shape=rectangle ];
    "webfx-cli" [shape=ellipse];
    "webfx.xml" -> "webfx-cli"
    "Your module source code" -> "webfx-cli"
    "webfx-cli" -> "pom.xml"
    "webfx-cli" -> "module-info.java"
    "webfx-cli" -> "GWT module.gwt.xml
super sources, bundles, etc..."
    "webfx-cli" -> "GraalVM conf"
}
----

Your inputs will be centralized in the WebFX module files named webfx.xml (same location as pom.xml), and the CLI will generate the rest of the build chain from them. For example, a typical directive in webfx.xml will be:

    <dependencies>
        <used-by-source-modules/>
    </dependencies>

This directive is asking the CLI to identify the list of your dependencies from an analysis of your source code, and automatically populate the dependencies in pom.xml, module-info.java, module.gwt.xml, etc...

During that process, the CLI takes care of the cross-platform aspects: when a feature is platform-dependent (a different implementation exists for different platforms), it will pick up the right modules (those whose implementation matches the target platform). This is at this point for example that it will replace the OpenJFX modules with the WebFX kit ones in your GWT application module.

=== Installing the WebFX CLI

Since we haven't published any release at this stage yet, the way to install the CLI for now is to clone the https://github.com/webfx-project/webfx-cli[webfx-cli] repository, and build it with Maven.

NOTE: We will distribute the CLI in a better way on the first WebFX official release.

==== Cloning the webfx-cli repository

[source,shell,indent=0,role="primary"]
.HTTPS
----
git clone https://github.com/webfx-project/webfx-cli.git
----

[source,shell,indent=0,role="secondary"]
.SSH
----
git clone git@github.com:webfx-project/webfx-cli.git
----

==== Building webfx-cli with Maven

This is achieved by running the Maven _package_ goal under the webfx-cli directory:

 cd webfx-cli
 mvn package

IMPORTANT: As previously mentioned, WebFX CLI requires JDK 13 or above to successfully compile.

This generates an executable fat jar in the target folder that we can execute with java:

 java -jar target/webfx-cli-0.1.0-SNAPSHOT-fat.jar --help

==== Creating a permanent _webfx_ alias

To easily invoke the CLI from a terminal, we need to create a permanent _webfx_ alias. This is done with the following commands (to run under the webfx-cli directory):

[source,shell,indent=0,role="primary"]
.Linux
----
echo "alias webfx='java -jar $(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")/target/webfx-cli-0.1.0-SNAPSHOT-fat.jar'" >> ~/.bashrc <1>

source ~/.bashrc <2>
----
<1> Adding the alias to the shell profile
<2> Applying it to the current session

[source,shell,indent=0,role="secondary"]
.macOS >= Catalina
----
echo "alias webfx='java -jar $(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")/target/webfx-cli-0.1.0-SNAPSHOT-fat.jar'" >> ~/.zshrc <1>

source ~/.zshrc <2>
----
<1> Adding the alias to the shell profile
<2> Applying it to the current session

[source,shell,indent=0,role="secondary"]
.macOS < Catalina
----
echo "alias webfx='java -jar $(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")/target/webfx-cli-0.1.0-SNAPSHOT-fat.jar'" >> ~/.bash_profile <1>

source ~/.bash_profile <2>
----
<1> Adding the alias to the shell profile
<2> Applying it to the current session

[source,shell,indent=0,role="secondary"]
.Windows PowerShell
----
If (!(Test-Path $profile)) { New-Item -Path $profile -Force } <1>

"`r`nfunction webfx([String[]] [Parameter(ValueFromRemainingArguments)] `$params) { java -jar $((Get-Item .).fullName)\target\webfx-cli-0.1.0-SNAPSHOT-fat.jar `$params }`r`n" >> $profile <2>

If ($(Get-ExecutionPolicy) -eq "Restricted") { Start-Process powershell -Verb runAs "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned" -Wait } <3>

. $profile <4>
----
<1> Creating a PowerShell profile if it doesn't exist
<2> Adding the alias (implemented as a function) to it
<3> Lowering the execution policy if necessary to execute the profile
<4> Applying it to the current session

Then you should be able to invoke the CLI from the terminal:

 webfx --help

==== Updating the WebFX CLI to the latest version

You can check for update at anytime by running:

 webfx bump cli

If a new version is available, it will download it and build it for you.

NOTE: This is the only command that uses `git`, and it's just a `git pull` of the webfx-cli repository. The CLI will not call `git` on your own repositories.

=== Creating your first WebFX app

==== Creating and initializing your repository

Let's create our first WebFX application. We need to create the repository directory and ask the CLI to initialize it, passing it the groupId, artifactId and version of our application.

 mkdir webfx-example
 cd webfx-example
 webfx init org.example:webfx-example:1.0.0-SNAPSHOT

TIP: `webfx init org.example:1.0.0-SNAPSHOT` will also work as the tool takes the repository directory name as the artifactId when omitted in the command.

==== Creating your application modules

 webfx create application --class org.example.webfxexample.WebFxExampleApplication --helloWorld

[plantuml, webfx-example-structure, format=svg]
----
skinparam Legend {
	BackgroundColor transparent
	BorderColor transparent
    FontSize 18
    FontColor #444
}
legend
webfx-example
|_ webfx-example-application
|_ webfx-example-application-gluon
|_ webfx-example-application-gwt
|_ webfx-example-application-openjfx
end legend
----
==== Building your application

 webfx build

==== Running your application

You can run the OpenJFX version of your application with the following command:

 webfx -m webfx-example-application-openjfx run

You can run the GWT version of your application with the following command:

 webfx -m webfx-example-application-gwt run

=== Developing in your IDE

We will give the instructions for IntelliJ IDEA, but you can easily transpose them to other Java IDEs.

==== Opening the project

==== Configuring the OpenJFX application

A few explanation before going further: GWT has a different entry point than standard Java applications, but WebFX hides the hassle with a single cross-platform entry point that will correctly bootstrap your application. So the main class of a WebFX application will always be `dev.webfx.platform.shared.services.boot.ApplicationBooter` whatever the platform. It will find your JavaFX application because it has been automatically declared as a Java service by the CLI.

NOTE: GWT normally doesn't support the Java service API, but WebFX does, because the CLI emulates it by generating a GWT super source. You can rely on this feature to declare and implement your own services. Your services can even have platform-dependent implementations. This can be a cross-platform UI API, with an OpenJFX implementation, and then a GWT implementation using an alternative JS library for your web app.

==== Building and running the GWT application

==== Making changes

 webfx update

ifdef::backend-html5[]
== PDF version
Here is the
link:WebFX.pdf[PDF version,float="right"]
of this documentation.
endif::[]
